### ISSUE TITLE
Add support for AoT compilation

### ISSUE THREAD

**Issue by Kaliumhexacyanoferrat** [Kaliumhexacyanoferrat/GenHTTP#606]
As a developer of a web service, I would like to natively compile my app, so that I can benefit from associated benefits.

**Note**

Webservice apps can currently be compiled natively, but there are some actions to be taken by devs which are not obvious.

**ToDos**

- [ ] Mark assemblies as AoT compatible where appropriate
- [ ] Annotate limitations (such as XML serialization) and disable them by default when in an AoT context
- [ ] Test module functionality (e.g. OpenAPI currently uses default JSON serialization which does not work ootb)
- [ ] Document the required steps to natively compile and run a program (in Docker as well)
- [ ] Document the existing limitations
